- name: Install OpenJDK package for Fedora Linux < 22
  yum:
    name={{item}}
    state=present
  changed_when: false
  when: ansible_distribution_major_version|int < 22
  with_items:
    - "java-1.{{ openjdk_version }}.0-openjdk"

- name:  Install package for Fedora Linux >= 22
  shell: dnf install {{item}} -y
  changed_when: false
  when: ansible_distribution_major_version|int >= 22
  with_items:
    - "java-1.{{ openjdk_version }}.0-openjdk"
