# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "bento/freebsd-10.2"
  # config.vm.base_mac = "5CA1AB1E0001"
  config.ssh.shell = "/bin/sh"
  # config.vm.synced_folder ".", "/vagrant", type: "nfs"

  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = false
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  config.vm.provision "shell", inline: <<-SHELL
    sudo pkg install -y portupgrade;
    sudo portsnap --interactive fetch extract
  #  sudo portsnap fetch update

  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    #ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.extra_vars = { ansible_python_interpreter: '/usr/local/bin/python2.7', freebsd_install_from_ports: 'False' }

  end
end
