# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "368"
  end
  config.vm.define :ubuntu_1404_i386 do |precise64|
    precise64.vm.box = "bento/ubuntu-14.04-i386"
    precise64.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define :ubuntu_1404_x64 do |precise64|
    precise64.vm.box = "bento/ubuntu-14.04"
    precise64.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end



