# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.define :fedora22_x64 do |fedora64|
    fedora64.vm.box = "bento/fedora-22"
    fedora64.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

end
